### ISSUE TITLE
Is it possible to specify the gender?

### ISSUE THREAD

**Issue by JoyceBabu** [multiavatar/multiavatar-php#1]
Interesting project.

Is it possible to specify the gender for the generated avatar?

**Comment by giekaton** [comment]
Thanks for the feedback.

Currently, it isn't possible to choose gender (or race) but since it's a common request (see multiavatar/Multiavatar#1), such functionality will probably be developed in the future.

**Comment by JoyceBabu** [comment]
Thank you.
